### ISSUE TITLE
Alternative parameterization of `roll_dst`

### ISSUE THREAD

**Issue by DavisVaughan** [vspinu/timechange#13]
I've been researching a lot about timechange, CCTZ, and the C++20 date library lately.

I think that `roll_dst` could be more intuitively represented as two separate arguments: one for DST gaps and one for DST fallbacks. This is inspired by the C++20 date library, from which we could borrow this terminology:

```r
time_force_tz(x, nonexistant = c("next", "NA", "error"), ambiguous = c("earliest", "latest", "NA", "error")
```

Some examples:

```r
# Clock time doesn't exist in America/New_York (in a gap)
x <- as.POSIXct("2010-03-14 02:05:05", "UTC")

time_force_tz(x, tz = "America/New_York", nonexistant = "next")
#> [1] "2010-03-14 03:00:00 EDT"

time_force_tz(x, tz = "America/New_York", nonexistant = "NA")
#> [1] "NA"

time_force_tz(x, tz = "America/New_York", nonexistant = "error")
#> Error: Nonexistant date error



# Two of these clock times in America/New_York (because of fallback)
y <- as.POSIXct("1970-10-25 01:00:00", "UTC")

time_force_tz(y, tz = "America/New_York", ambiguous = "earliest")
#> [1] "1970-10-25 01:00:00 EDT"

time_force_tz(y, tz = "America/New_York", ambiguous = "latest")
#> [1] "1970-10-25 01:00:00 EST"

time_force_tz(y, tz = "America/New_York", ambiguous = "NA")
#> [1] "NA"

time_force_tz(y, tz = "America/New_York", ambiguous = "error")
#> Error: Ambiguous date error
```

I see that you also have first/last options, but I have to imagine that when you have a gap that the most common thing is to just roll to the "next" available time or return an NA. Could you explain why keeping the minutes and seconds here is useful?

```r
time_force_tz(x, tz = "America/New_York", roll_dst = "first")
#> [1] "2010-03-14 03:05:05 EDT"

time_force_tz(x, tz = "America/New_York", roll_dst = "last")
#> [1] "2010-03-14 01:05:05 EST"
```

I have not fully thought out how this could be used with arithmetic, but I think it is perfectly reasonable that `time_add()` could have different DST options (for example, "skip" seems relevant there)

**Comment by vspinu** [comment]
Thanks for the proposal. II plan to move lubridate on top of timechange by the end of the year, so it's a very timely discussion. The current situation is clearly not satisfactory. Seems like I planned to change first/last into next/prev actually. 

The current design has an advantage that month and DST gaps can be treated separately. Your proposal has an advantage that non-existent and ambiguous cases can be treated differently. We could deal with it by allowing a 2 element spec like `nonexistent = c("next", "prev")`, or maybe `list(month = "next", dst = "prev")`.

I also have "skip" (which can be maybe better named "asis" or "raw"). How about the following:

```
nonexistent = c("next", "prev", "nextkeep", "prevkeep", "NA", "skip", "error")
ambiguous = c("earliest", "latest", "NA", "error")
```

>  I have to imagine that when you have a gap that the most common thing is to just roll to the "next" available time or return an NA

The most common use case is last day of the month, when you do `2020-01-31 01:02:03 + 1 month`. In this case it makes total sense to preserve smaller units. For DST it's less clear, butt similar logic applies. Think `1970-10-25 00:15:00 EDT + 1H`.  Also with multiple operations in a row x + y + z it could be surprising to see that MM:SS disappeared. 

> and the C++20 date library lately.

And what's your opinion? Is it inspired by CCTZ, can it eventually replace it?

**Comment by vspinu** [comment]
I have finally spent some time on this and the new interface allows for separate behavior of `roll_dst`. Both `skipped` and `repeated` DST transitions accept `pre`, `boundary`, `post` and `NA`.  Should probably add `error` per your suggestion :thinking: 

Regarding treating month and DST rolling in one pile with the same configuration it's a no go I am afraid. First, for historical reasons, lubridate does not provide the consistent treatment for those and a separate config would be needed. Second, I really think those are quite different beasts conceptually. 

I am finally rebasing lubridate on top of `timechange` in the next release. Thanks for all of your input!

**Comment by DavisVaughan** [comment]
I think you, me, and @hadley should set aside some time to talk about this because we are also considering the idea of using clock as the lubridate backend

**Comment by vspinu** [comment]
I have just spent 3 days on [porting it on timechange](https://github.com/tidyverse/lubridate/commits/timechange) and figuring all the quirks and inconsistencies of lubridate in order to keep it backward compatible. Given that `clock` is a major paradigm shift it would probably require a massive amount of work and essentially a rewrite of lubridate. So I don't see much point in doing that.

`timechange` is quite similar to lubridate conceptually but with a cleaner, program-oriented API. It maps almost one-on-one to lubridate functionality. So it was relatively easy to integrate.

IMO, f you have time to spare, then better jump-start a new package alternative to lubridate and stop fighting with backward compatibility.

**Comment by hadley** [comment]
Sorry, we didn’t mean to blindside you with the suggestion to use clock as a backend for lubridate instead of timechange. We’ve been talking a bit about this internally for a while and had planned to have a conversation with you later in the year (none of us had been working on lubridate lately so we thought we had some time).

You’re absolutely right that it would be much less work (and likely much more fun!) to build a new “lubridate2” from scratch, rather than retrofitting the existing package. But it’s also a big lift to get folks to use a new package, and the delta for lubridate2 over lubridate would be much smaller than lubridate over base R. This is why we were hoping to harmonize the better algorithms that back clock with lubridate (while recognising there’s a bunch of work to figure out how that might work).

I think we’d also generally prefer that hard dependencies of tidyverse packages live in tidyverse or r-lib. I’m not sure if you heard about it, but CRAN recently threatened to pull isoband (a ggplot2 dependency) from CRAN, causing >4000 maintainers to get an email, because the maintainer was on vacation and didn’t rapidly fix a minor clang compilation issue. We want to keep contributions to the tidyverse as open as possible, but we also don’t want to put folks on the hook for rapid fixes when we all get paid to do it full-time.

**Comment by vspinu** [comment]
I am open to any approach but, honestly, I do have my reservations regarding clock. It's a pretty heavy package - it takes 5 minutes to compile on my oldish laptop and the number of functions is mind bending. The functionality does not map strighforwardly to lubridate. Stuff which is abstracted in lubridate with parameters and data-types (like period) are abstracted into separate functions in clock. As far as I can judge on a first glance, lubridate's `update` functionality and `rounding` cannot even be implemented using clock's API in any straightforward manner.

> I think we’d also generally prefer that hard dependencies of tidyverse packages live in tidyverse or r-lib. 

I would be honored to host it there. In my view it's not a big deal if there are several alternative packages doing similar things on tidyverse. But it's your call.

**Comment by hadley** [comment]
Ok, if you're fine with it, lets move timechange to r-lib. There's just one ask: if you ever get sick of maintaining timechange, you give us the right to take over maintenance (we wouldn't do it without asking). If that's ok with you, I'll send you an invite to r-lib, and you can transfer the repo over.

Then later next year we can figure out exactly where lubridate and clock are going, and if it's worth combining them in some way.

**Comment by vspinu** [comment]
>  you ever get sick of maintaining timechange, you give us the right to take over maintenance (we wouldn't do it without asking).

Of course!
